package com.project.views;

import com.project.controller.ViewAllProjectsController;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Priya
 */
@SuppressWarnings("serial")
public class AdminViewGui extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewGui
     */
    ViewAllProjectsController vieweAllProjectsController;
	String startDate;
	String theme;
	String student_id;
	String project_id;
	String faculty_id;
        String scope;
        String partner;
    public AdminViewGui() {
		initComponents();
		vieweAllProjectsController = new ViewAllProjectsController(this);
		addJTables();
	}
	
	public String getProject_id() {
		return project_id;
	}

	public void setProject_id(String project_id) {
		this.project_id = project_id;
	}
        
    private void addJTables() {
		// TODO Auto-generated method stub

		jTableProjectDetails = new JTable(
				vieweAllProjectsController.getTableModel());
		jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
		
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
		
		
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanelUserOptions = new javax.swing.JPanel();
        btnViewDetails = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanelAdminOptions = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanelProjectDetails = new javax.swing.JPanel();
        jProjectDetailsScrollPane = new javax.swing.JScrollPane();
        jTableProjectDetails = new javax.swing.JTable();
        menuMain = new javax.swing.JMenuBar();
        menuQuery = new javax.swing.JMenu();
        menuStatus = new javax.swing.JMenu();
        itemActive = new javax.swing.JMenuItem();
        itemComplete = new javax.swing.JMenuItem();
        itemSuspended = new javax.swing.JMenuItem();
        itemAborted = new javax.swing.JMenuItem();
        menuTimelines = new javax.swing.JMenu();
        itemStartDate = new javax.swing.JMenuItem();
        itemScope = new javax.swing.JMenuItem();
        menuPeople = new javax.swing.JMenu();
        itemPartners = new javax.swing.JMenuItem();
        itemStudents = new javax.swing.JMenuItem();
        itemAdvisors = new javax.swing.JMenuItem();
        itemTheme = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Project Screen");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 600, 400));
        setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Frugal_Blk_BriteRed_72dpi.jpg"))); // NOI18N

        jPanelUserOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnViewDetails.setFont(getFont());
        btnViewDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/detail_icon.png"))); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnLogOut.setFont(getFont());
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout_icon.png"))); // NOI18N
        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnReset.setFont(getFont());
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset_icon.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUserOptionsLayout = new javax.swing.GroupLayout(jPanelUserOptions);
        jPanelUserOptions.setLayout(jPanelUserOptionsLayout);
        jPanelUserOptionsLayout.setHorizontalGroup(
            jPanelUserOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUserOptionsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewDetails)
                .addGap(159, 159, 159)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanelUserOptionsLayout.setVerticalGroup(
            jPanelUserOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnLogOut))
                .addContainerGap())
        );

        jPanelAdminOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnAdd.setFont(getFont());
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_icon.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setFont(getFont());
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_icon.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(getFont());
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete_icon.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminOptionsLayout = new javax.swing.GroupLayout(jPanelAdminOptions);
        jPanelAdminOptions.setLayout(jPanelAdminOptionsLayout);
        jPanelAdminOptionsLayout.setHorizontalGroup(
            jPanelAdminOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminOptionsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanelAdminOptionsLayout.setVerticalGroup(
            jPanelAdminOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdminOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProjectDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ProjectDetails", 0, 0, getFont()));
        jPanelProjectDetails.setFont(getFont());

        jTableProjectDetails.setFont(getFont());
        jTableProjectDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);

        javax.swing.GroupLayout jPanelProjectDetailsLayout = new javax.swing.GroupLayout(jPanelProjectDetails);
        jPanelProjectDetails.setLayout(jPanelProjectDetailsLayout);
        jPanelProjectDetailsLayout.setHorizontalGroup(
            jPanelProjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProjectDetailsScrollPane)
                .addContainerGap())
        );
        jPanelProjectDetailsLayout.setVerticalGroup(
            jPanelProjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjectDetailsLayout.createSequentialGroup()
                .addComponent(jProjectDetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelUserOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAdminOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelProjectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblLogo)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(33, 33, 33)
                .addComponent(jPanelUserOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAdminOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanelProjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        menuQuery.setText("Query");
        menuQuery.setFont(getFont());

        menuStatus.setText("Status");
        menuStatus.setFont(getFont());

        itemActive.setFont(getFont());
        itemActive.setText("Active");
        itemActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActiveActionPerformed(evt);
            }
        });
        menuStatus.add(itemActive);

        itemComplete.setFont(getFont());
        itemComplete.setText("Completed");
        itemComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompleteActionPerformed(evt);
            }
        });
        menuStatus.add(itemComplete);

        itemSuspended.setFont(getFont());
        itemSuspended.setText("Suspended");
        itemSuspended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSuspendedActionPerformed(evt);
            }
        });
        menuStatus.add(itemSuspended);

        itemAborted.setFont(getFont());
        itemAborted.setText("Aborted");
        itemAborted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbortedActionPerformed(evt);
            }
        });
        menuStatus.add(itemAborted);

        menuQuery.add(menuStatus);

        menuTimelines.setText("Timelines & Scope");
        menuTimelines.setFont(getFont());

        itemStartDate.setText("Start Date");
        itemStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStartDateActionPerformed(evt);
            }
        });
        menuTimelines.add(itemStartDate);

        itemScope.setText("Scope");
        itemScope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemScopeActionPerformed(evt);
            }
        });
        menuTimelines.add(itemScope);

        menuQuery.add(menuTimelines);

        menuPeople.setText("People");
        menuPeople.setFont(getFont());

        itemPartners.setFont(getFont());
        itemPartners.setText("Partners");
        itemPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPartnersActionPerformed(evt);
            }
        });
        menuPeople.add(itemPartners);

        itemStudents.setFont(getFont());
        itemStudents.setText("Students");
        itemStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStudentsActionPerformed(evt);
            }
        });
        menuPeople.add(itemStudents);

        itemAdvisors.setFont(getFont());
        itemAdvisors.setText("Advisors");
        itemAdvisors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdvisorsActionPerformed(evt);
            }
        });
        menuPeople.add(itemAdvisors);

        menuQuery.add(menuPeople);

        itemTheme.setFont(getFont());
        itemTheme.setText("Theme /Category");
        itemTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemThemeActionPerformed(evt);
            }
        });
        menuQuery.add(itemTheme);

        menuMain.add(menuQuery);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("ProjectList");

        pack();
    }// </editor-fold>

    private void itemThemeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ThemeCategoryDialog themeDialog = new ThemeCategoryDialog(this, rootPaneCheckingEnabled);
    	themeDialog.setLocation(80, 80);
    	themeDialog.setVisible(true);
    	
    	if(theme!=null)
        {
    		setProject_id(null);
        	jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithTheme(theme));
        	jTableProjectDetails.getSelectionModel().addListSelectionListener(
					vieweAllProjectsController);
        	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
    		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
        }
    }                                         

    private void itemActiveActionPerformed(java.awt.event.ActionEvent evt) {                                           
       setProject_id(null);
        jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithStatus("Active"));
        jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
    	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
       
        jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
    }                                          

    private void itemCompleteActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        setProject_id(null);
        jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithStatus("Completed"));
        jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
    	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
		
		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
    }                                            

    private void itemAbortedActionPerformed(java.awt.event.ActionEvent evt) {                                            
        setProject_id(null);
        jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithStatus("Aborted"));
        jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
    	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
    }                                           

    private void itemStudentsActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        StudentDialog studentDialog = new StudentDialog(this,
				rootPaneCheckingEnabled);
		studentDialog.setLocation(80, 80);
		studentDialog.setVisible(true);
		if (student_id != null) {
			//studentController = new StudentTableController(this);
			setProject_id(null);
			jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithStudentId(student_id));
			jTableProjectDetails.getSelectionModel().addListSelectionListener(
					vieweAllProjectsController);
			jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
			
			jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
                }
    }                                            

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
			
			ProjectDetailsAddForm form = new ProjectDetailsAddForm();
			form.setVisible(true);
		
		
    }                                      

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (project_id != null) {
			ProjectDetailsEdit form = new ProjectDetailsEdit(getProject_id());
			form.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(this, "Please select a project");
		}
    }                                       

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
       if (project_id != null) {
			jTableProjectDetails = new JTable(vieweAllProjectsController.deleteProject(project_id));
			jTableProjectDetails.getSelectionModel().addListSelectionListener(
					vieweAllProjectsController);
			jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
			
			jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
			project_id = null;
		} else {
			JOptionPane.showMessageDialog(this, "Please select a project");
		}
    }                                         

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
       setProject_id(null);
    	vieweAllProjectsController = new ViewAllProjectsController(this);
    	addJTables();
    }                                        

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {                                               
         if (project_id != null) {
			
			ViewerProjectDetailsForm form = new ViewerProjectDetailsForm(getProject_id());
			form.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(this, "Please select a project");
		}
    }                                              

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.setVisible(false);
       this.dispose();
       ViewerGUI viewgui = new ViewerGUI();
       viewgui.setVisible(true);
    }                                         

    private void itemSuspendedActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        setProject_id(null);
        jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithStatus("Suspended"));
        jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
    	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
		
		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
    }                                             

    private void itemStartDateActionPerformed(java.awt.event.ActionEvent evt) {                                              
        SelectStartDate startDateDialog = new SelectStartDate(this, rootPaneCheckingEnabled);
        startDateDialog.setLocation(80, 80);
        startDateDialog.setPreferredSize(new Dimension(50,50));
        startDateDialog.setVisible(true);
        if(startDate!=null)
        {
        	setProject_id(null);
        	jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithDate(startDate));
        	 jTableProjectDetails.getSelectionModel().addListSelectionListener(
     				vieweAllProjectsController);
        	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
    		
    		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
        }
    }                                             

    private void itemScopeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ScopeDialog scopeDialog = new ScopeDialog(this, rootPaneCheckingEnabled);
   	 scopeDialog.setLocation(80, 80);
   	 scopeDialog.setVisible(true);
    	
    	if(scope!=null)
        {
    		setProject_id(null);
        	jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithScope(scope));
        	jTableProjectDetails.getSelectionModel().addListSelectionListener(
					vieweAllProjectsController);
        	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
    		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
        }
    }                                         

    private void itemPartnersActionPerformed(java.awt.event.ActionEvent evt) {                                             
       PartnerDialog partnerDialog = new PartnerDialog(this, rootPaneCheckingEnabled);
    	partnerDialog.setLocation(80, 80);
    	partnerDialog.setVisible(true);
    	
    	if(partner!=null)
        {
    		setProject_id(null);
        	jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithPartner(partner));
        	jTableProjectDetails.getSelectionModel().addListSelectionListener(
					vieweAllProjectsController);
        	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
    		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
        }
    }                                            

    private void itemAdvisorsActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
         FacultyDialog facultyDialog = new FacultyDialog(this,
 				rootPaneCheckingEnabled);
    	facultyDialog.setLocation(80, 80);
    	facultyDialog.setVisible(true);
 		if (faculty_id != null) {
 			//studentController = new StudentTableController(this);
 			setProject_id(null);
 			jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithFacultyId(faculty_id));
 			jTableProjectDetails.getSelectionModel().addListSelectionListener(
 					vieweAllProjectsController);
 			jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
 			
 			jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
 			
 		}
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdminViewGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JMenuItem itemAborted;
    private javax.swing.JMenuItem itemActive;
    private javax.swing.JMenuItem itemAdvisors;
    private javax.swing.JMenuItem itemComplete;
    private javax.swing.JMenuItem itemPartners;
    private javax.swing.JMenuItem itemScope;
    private javax.swing.JMenuItem itemStartDate;
    private javax.swing.JMenuItem itemStudents;
    private javax.swing.JMenuItem itemSuspended;
    private javax.swing.JMenuItem itemTheme;
    private javax.swing.JPanel jPanelAdminOptions;
    private javax.swing.JPanel jPanelProjectDetails;
    private javax.swing.JPanel jPanelUserOptions;
    private javax.swing.JScrollPane jProjectDetailsScrollPane;
    private javax.swing.JTable jTableProjectDetails;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuPeople;
    private javax.swing.JMenu menuQuery;
    private javax.swing.JMenu menuStatus;
    private javax.swing.JMenu menuTimelines;
    // End of variables declaration
}
