/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.views;

import com.project.controller.ViewAllProjectsController;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author Priya
 */
@SuppressWarnings("serial")
public class ViewerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewerGui
     */
    
    ViewAllProjectsController vieweAllProjectsController;
     String startDate;
     String theme;
     String student_id;
     String project_id;
     String faculty_id;
     String scope;
     String partner;
    public ViewerGUI() {
        initComponents();
        vieweAllProjectsController = new ViewAllProjectsController(this);
		addJTables();
    }
    
     public String getProject_id() {
		return project_id;
	}

	public void setProject_id(String project_id) {
		this.project_id = project_id;
	}
        
    private void addJTables() {
		// TODO Auto-generated method stub

		jTableProjectDetails = new JTable(
				vieweAllProjectsController.getTableModel());
		jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
		
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
		
		
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lblLogo1 = new javax.swing.JLabel();
        jPanelProjectDetails = new javax.swing.JPanel();
        jProjectDetailsScrollPane = new javax.swing.JScrollPane();
        jTableProjectDetails = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnViewAllDetails = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        menuMain = new javax.swing.JMenuBar();
        menuQuery = new javax.swing.JMenu();
        menuStatus = new javax.swing.JMenu();
        itemActive = new javax.swing.JMenuItem();
        itemCompleted = new javax.swing.JMenuItem();
        itemSuspended = new javax.swing.JMenuItem();
        itemAborted = new javax.swing.JMenuItem();
        menuTimeline = new javax.swing.JMenu();
        itemStartDate = new javax.swing.JMenuItem();
        itemScope = new javax.swing.JMenuItem();
        menuPeople = new javax.swing.JMenu();
        itemPartner = new javax.swing.JMenuItem();
        itemStudents = new javax.swing.JMenuItem();
        itemAdvisor = new javax.swing.JMenuItem();
        itemTheme = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Viewer Project Screen");
        setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 400));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setFont(getFont());

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Frugal_Blk_BriteRed_72dpi.jpg"))); // NOI18N

        jPanelProjectDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ProjectDetails", 0, 0, getFont()));
        jPanelProjectDetails.setToolTipText("");
        jPanelProjectDetails.setFont(getFont());

        jTableProjectDetails.setFont(getFont());
        jTableProjectDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);

        javax.swing.GroupLayout jPanelProjectDetailsLayout = new javax.swing.GroupLayout(jPanelProjectDetails);
        jPanelProjectDetails.setLayout(jPanelProjectDetailsLayout);
        jPanelProjectDetailsLayout.setHorizontalGroup(
            jPanelProjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProjectDetailsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelProjectDetailsLayout.setVerticalGroup(
            jPanelProjectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProjectDetailsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnReset.setFont(getFont());
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset_icon.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnViewAllDetails.setFont(getFont());
        btnViewAllDetails.setForeground(new java.awt.Color(51, 51, 51));
        btnViewAllDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/detail_icon.png"))); // NOI18N
        btnViewAllDetails.setText("View Details");
        btnViewAllDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllDetailsActionPerformed(evt);
            }
        });

        jButtonLogin.setFont(getFont());
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login_icon.png"))); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnViewAllDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnViewAllDetails)
                    .addComponent(jButtonLogin))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelProjectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblLogo1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(lblLogo1)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanelProjectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuMain.setFont(getFont());

        menuQuery.setText("Query");
        menuQuery.setFont(getFont());

        menuStatus.setText("Status");
        menuStatus.setFont(getFont());

        itemActive.setFont(getFont());
        itemActive.setText("Active");
        itemActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActiveActionPerformed(evt);
            }
        });
        menuStatus.add(itemActive);

        itemCompleted.setFont(getFont());
        itemCompleted.setText("Completed");
        itemCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompletedActionPerformed(evt);
            }
        });
        menuStatus.add(itemCompleted);

        itemSuspended.setFont(getFont());
        itemSuspended.setText("Suspended");
        itemSuspended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSuspendedActionPerformed(evt);
            }
        });
        menuStatus.add(itemSuspended);

        itemAborted.setFont(getFont());
        itemAborted.setText("Aborted");
        itemAborted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbortedActionPerformed(evt);
            }
        });
        menuStatus.add(itemAborted);

        menuQuery.add(menuStatus);

        menuTimeline.setText("Timelines & Scope");
        menuTimeline.setFont(getFont());

        itemStartDate.setFont(getFont());
        itemStartDate.setText("Start Date");
        itemStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStartDateActionPerformed(evt);
            }
        });
        menuTimeline.add(itemStartDate);

        itemScope.setFont(getFont());
        itemScope.setText("Scope");
        itemScope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemScopeActionPerformed(evt);
            }
        });
        menuTimeline.add(itemScope);

        menuQuery.add(menuTimeline);

        menuPeople.setText("People");
        menuPeople.setFont(getFont());
        menuPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPeopleActionPerformed(evt);
            }
        });

        itemPartner.setFont(getFont());
        itemPartner.setText("Partners");
        itemPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPartnerActionPerformed(evt);
            }
        });
        menuPeople.add(itemPartner);

        itemStudents.setFont(getFont());
        itemStudents.setText("Students");
        itemStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStudentsActionPerformed(evt);
            }
        });
        menuPeople.add(itemStudents);

        itemAdvisor.setFont(getFont());
        itemAdvisor.setText("Advisors");
        itemAdvisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdvisorActionPerformed(evt);
            }
        });
        menuPeople.add(itemAdvisor);

        menuQuery.add(menuPeople);

        itemTheme.setFont(getFont());
        itemTheme.setText("Theme/Category");
        itemTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemThemeActionPerformed(evt);
            }
        });
        menuQuery.add(itemTheme);

        menuMain.add(menuQuery);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void itemActiveActionPerformed(java.awt.event.ActionEvent evt) {                                           
        setProject_id(null);
        jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithStatus("Active"));
        jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
    	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
       
        jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
    }                                          

    private void itemCompletedActionPerformed(java.awt.event.ActionEvent evt) {                                              
        setProject_id(null);
        jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithStatus("Completed"));
        jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
    	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
		
		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
    }                                             

    private void itemStartDateActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        SelectStartDate startDateDialog = new SelectStartDate(this, rootPaneCheckingEnabled);
        startDateDialog.setLocation(80, 80);
        startDateDialog.setPreferredSize(new Dimension(50,50));
        startDateDialog.setVisible(true);
        if(startDate!=null)
        {
        	setProject_id(null);
        	jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithDate(startDate));
        	 jTableProjectDetails.getSelectionModel().addListSelectionListener(
     				vieweAllProjectsController);
        	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
    		
    		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
        }
    }                                             

    private void itemAdvisorActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        FacultyDialog facultyDialog = new FacultyDialog(this,
 				rootPaneCheckingEnabled);
    	facultyDialog.setLocation(80, 80);
    	facultyDialog.setVisible(true);
 		if (faculty_id != null) {
 			//studentController = new StudentTableController(this);
 			setProject_id(null);
 			jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithFacultyId(faculty_id));
 			jTableProjectDetails.getSelectionModel().addListSelectionListener(
 					vieweAllProjectsController);
 			jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
 			
 			jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
 			
 		}
    }                                           

    private void itemSuspendedActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        setProject_id(null);
        jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithStatus("Suspended"));
        jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
    	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
		
		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
    }                                             

    private void menuPeopleActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void itemStudentsActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        StudentDialog studentDialog = new StudentDialog(this,
				rootPaneCheckingEnabled);
		studentDialog.setLocation(80, 80);
		studentDialog.setVisible(true);
		if (student_id != null) {
			//studentController = new StudentTableController(this);
			setProject_id(null);
			jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithStudentId(student_id));
			jTableProjectDetails.getSelectionModel().addListSelectionListener(
					vieweAllProjectsController);
			jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
			
			jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
//			jstudentDetails = new JTable(studentController.getStudentsWithId(student_id));
//			for(int i = 0;i < jTableProjectDetails.getRowCount();i++)
//			{
//				jTableProjectDetails.addColumn(jstudentDetails.getColumn("student_id"));
//				jTableProjectDetails.addColumn(jstudentDetails.getColumn("name"));
//			}
			
		}
    }                                            

    private void itemAbortedActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        setProject_id(null);
        jTableProjectDetails  = new JTable(vieweAllProjectsController.getProjectWithStatus("Aborted"));
        jTableProjectDetails.getSelectionModel().addListSelectionListener(
				vieweAllProjectsController);
    	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
    }                                           

    private void itemThemeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ThemeCategoryDialog themeDialog = new ThemeCategoryDialog(this, rootPaneCheckingEnabled);
    	themeDialog.setLocation(80, 80);
    	themeDialog.setVisible(true);
    	
    	if(theme!=null)
        {
    		setProject_id(null);
        	jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithTheme(theme));
        	jTableProjectDetails.getSelectionModel().addListSelectionListener(
					vieweAllProjectsController);
        	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
    		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
        }
    }                                         

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        setProject_id(null);
    	vieweAllProjectsController = new ViewAllProjectsController(this);
    	addJTables();
    }                                        

    private void btnViewAllDetailsActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        if (project_id != null) {
			
			ViewerProjectDetailsForm form = new ViewerProjectDetailsForm(getProject_id());
			form.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(this, "Please select a project");
		}
    }                                                 

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {                                             
        LoginDialog loginDialog = new LoginDialog(this, rootPaneCheckingEnabled);
    	loginDialog.setLocation(80, 80);
    	loginDialog.setPreferredSize(new Dimension(50,50));
    	loginDialog.setVisible(true);
    }                                            

    private void itemPartnerActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        PartnerDialog partnerDialog = new PartnerDialog(this, rootPaneCheckingEnabled);
    	partnerDialog.setLocation(80, 80);
    	partnerDialog.setVisible(true);
    	
    	if(partner!=null)
        {
    		setProject_id(null);
        	jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithPartner(partner));
        	jTableProjectDetails.getSelectionModel().addListSelectionListener(
					vieweAllProjectsController);
        	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
    		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
        }
    }                                           

    private void itemScopeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ScopeDialog scopeDialog = new ScopeDialog(this, rootPaneCheckingEnabled);
    	 scopeDialog.setLocation(80, 80);
    	 scopeDialog.setVisible(true);
     	
     	if(scope!=null)
         {
     		setProject_id(null);
         	jTableProjectDetails = new JTable(vieweAllProjectsController.getProjectWithScope(scope));
         	jTableProjectDetails.getSelectionModel().addListSelectionListener(
 					vieweAllProjectsController);
         	jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("project_id"));
		jTableProjectDetails.removeColumn(jTableProjectDetails
				.getColumn("location"));
		jTableProjectDetails.getColumn("project_name").setHeaderValue("Project Name");
		jTableProjectDetails.getColumn("status").setHeaderValue("Status");
		jTableProjectDetails.getColumn("theme").setHeaderValue("Theme");
		jTableProjectDetails.getColumn("scope").setHeaderValue("Scope");
		jTableProjectDetails.getColumn("start_date").setHeaderValue("Start Date");
		jTableProjectDetails.getColumn("end_date").setHeaderValue("End Date");
     		jProjectDetailsScrollPane.setViewportView(jTableProjectDetails);
         }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewerGUI().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnViewAllDetails;
    private javax.swing.JMenuItem itemAborted;
    private javax.swing.JMenuItem itemActive;
    private javax.swing.JMenuItem itemAdvisor;
    private javax.swing.JMenuItem itemCompleted;
    private javax.swing.JMenuItem itemPartner;
    private javax.swing.JMenuItem itemScope;
    private javax.swing.JMenuItem itemStartDate;
    private javax.swing.JMenuItem itemStudents;
    private javax.swing.JMenuItem itemSuspended;
    private javax.swing.JMenuItem itemTheme;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelProjectDetails;
    private javax.swing.JScrollPane jProjectDetailsScrollPane;
    private javax.swing.JTable jTableProjectDetails;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuPeople;
    private javax.swing.JMenu menuQuery;
    private javax.swing.JMenu menuStatus;
    private javax.swing.JMenu menuTimeline;
    // End of variables declaration
}
